// Hors ligne : tout le paquet est mis en cache à la première visite.
// Version generated by scripts/sync_site.py; keep each hosted project’s caches separate.
const CACHE_VERSION='72e66f8d85f364b9';
const CACHE_PREFIX='inga:'+self.registration.scope+':';
const CACHE=CACHE_PREFIX+CACHE_VERSION;
const FILES=["./", "VERSION", "alternator-drawing.js", "alternator.css", "alternator.js", "canal-drawing.js", "canal.css", "canal.js", "fonts/architects-daughter-latin-400-normal.woff2", "fonts/architects-daughter-latin-ext-400-normal.woff2", "fonts/fonts.css", "fonts/ibm-plex-mono-latin-400-normal.woff2", "fonts/ibm-plex-mono-latin-500-normal.woff2", "fonts/ibm-plex-mono-latin-ext-400-normal.woff2", "fonts/ibm-plex-mono-latin-ext-500-normal.woff2", "fonts/ibm-plex-sans-condensed-latin-400-normal.woff2", "fonts/ibm-plex-sans-condensed-latin-500-normal.woff2", "fonts/ibm-plex-sans-condensed-latin-600-normal.woff2", "fonts/ibm-plex-sans-condensed-latin-700-normal.woff2", "fonts/ibm-plex-sans-condensed-latin-ext-400-normal.woff2", "fonts/ibm-plex-sans-condensed-latin-ext-500-normal.woff2", "fonts/ibm-plex-sans-condensed-latin-ext-600-normal.woff2", "fonts/ibm-plex-sans-condensed-latin-ext-700-normal.woff2", "fonts/ibm-plex-sans-latin-400-normal.woff2", "fonts/ibm-plex-sans-latin-500-normal.woff2", "fonts/ibm-plex-sans-latin-600-normal.woff2", "fonts/ibm-plex-sans-latin-ext-400-normal.woff2", "fonts/ibm-plex-sans-latin-ext-500-normal.woff2", "fonts/ibm-plex-sans-latin-ext-600-normal.woff2", "icons/icon-192.png", "icons/icon-512.png", "index.html", "journey-audio.js", "journey-endpoints.css", "journey-endpoints.js", "journey.css", "journey.js", "lib/OrbitControls.js", "lib/three.min.js", "manifest.webmanifest", "musee.html", "offline.css", "offline.js", "polish.css", "polish.js", "product.css", "product.js", "transformer-drawing.js", "transformer-model.js", "transformer.css", "transformer.js", "voix/journey-alternator.mp3", "voix/journey-canal.mp3", "voix/journey-city.mp3", "voix/journey-river.mp3", "voix/journey-transformer.mp3", "voix/journey-turbine.mp3", "voix/stop1.mp3", "voix/stop2.mp3", "voix/stop3.mp3", "voix/stop4.mp3", "voix/stop5.mp3", "voix/stop6.mp3", "voix/stop7.mp3", "voix/stop8.mp3"];
// A partial download is never presented as ready. First installs can still serve
// already cached resources; updates wait for an explicit choice in the app.
let downloadTask=null;
let phase='idle';
let failures=[];

async function status(){
  const cache=await caches.open(CACHE);
  const found=await Promise.all(FILES.map(path=>cache.match(new URL(path,self.registration.scope))));
  const cached=found.filter(Boolean).length;
  return {type:'INGA_OFFLINE_STATUS',version:CACHE_VERSION,total:FILES.length,cached,
    ready:cached===FILES.length,phase,failed:failures.length};
}
async function broadcast(){
  const data=await status();
  const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});
  clients.forEach(client=>client.postMessage(data));
}
async function download(){
  if(downloadTask) return downloadTask;
  downloadTask=(async()=>{
    phase='downloading'; failures=[];
    const cache=await caches.open(CACHE);
    const pending=[];
    for(const path of FILES){
      const url=new URL(path,self.registration.scope);
      if(!await cache.match(url)) pending.push(url);
    }
    await broadcast();
    let next=0;
    await Promise.all(Array.from({length:Math.min(4,pending.length)},async()=>{
      while(next<pending.length){
        const url=pending[next++];
        const controller=new AbortController();
        const timeout=setTimeout(()=>controller.abort(),20000);
        try{
          const response=await fetch(new Request(url,{cache:'reload',credentials:'same-origin',signal:controller.signal}));
          if(!response.ok) throw new Error('HTTP '+response.status);
          await cache.put(url,response);
        }catch(error){ failures.push(url.pathname); }
        finally{clearTimeout(timeout);}
        await broadcast();
      }
    }));
    phase=failures.length?'incomplete':'idle';
    await broadcast();
  })().finally(()=>{downloadTask=null;});
  return downloadTask;
}
function understandsUpdates(worker){
  return new Promise(resolve=>{
    const channel=new MessageChannel();
    const timeout=setTimeout(()=>{channel.port1.close();resolve(false);},5000);
    channel.port1.onmessage=()=>{clearTimeout(timeout);channel.port1.close();resolve(true);};
    try{worker.postMessage({type:'INGA_OFFLINE_PROTOCOL'},[channel.port2]);}
    catch(error){clearTimeout(timeout);channel.port1.close();resolve(false);}
  });
}
self.addEventListener('install',event=>{
  event.waitUntil((async()=>{
    const active=self.registration.active;
    const legacy=active&&!await understandsUpdates(active);
    await download();
    // Older releases have no update button. Migrate their worker once complete,
    // without reloading any client; the next navigation receives the new UI.
    if(legacy&&!(await status()).ready)throw new Error('Legacy migration is incomplete');
    if(!active||legacy)await self.skipWaiting();
  })());
});
self.addEventListener('activate',event=>{
  event.waitUntil((async()=>{
    // Keep a previous complete cache if this first install is incomplete.
    // Only this deployment scope is ours to clean up.
    if((await status()).ready){
      const keys=await caches.keys();
      await Promise.all(keys.filter(key=>key.startsWith(CACHE_PREFIX)&&key!==CACHE).map(key=>caches.delete(key)));
    }
    await self.clients.claim();
    await broadcast();
  })());
});
self.addEventListener('message',event=>{
  const command=event.data&&event.data.type;
  if(command==='INGA_OFFLINE_PROTOCOL'){
    if(event.ports[0])event.ports[0].postMessage({version:CACHE_VERSION});
  }else if(command==='INGA_OFFLINE_STATUS'){
    event.waitUntil(status().then(data=>{
      if(event.ports[0]) event.ports[0].postMessage(data);
      else if(event.source) event.source.postMessage(data);
    }));
  }else if(command==='INGA_OFFLINE_RETRY'){
    event.waitUntil(download());
  }else if(command==='INGA_OFFLINE_ACTIVATE'){
    event.waitUntil(status().then(data=>{if(data.ready)return self.skipWaiting();}));
  }
});
// Media players can request byte ranges, including during offline playback on mobile.
async function cachedMediaRange(request,response){
  const range=request.headers.get('Range');
  if(!range||response.status!==200||!new URL(request.url).pathname.endsWith('.mp3'))return response;
  const match=/^bytes=(\d*)-(\d*)$/i.exec(range);
  if(!match||(!match[1]&&!match[2]))return response;
  const bytes=await response.arrayBuffer(),size=bytes.byteLength;
  const start=match[1]?Number(match[1]):Math.max(0,size-Number(match[2]));
  const end=match[1]&&match[2]?Math.min(Number(match[2]),size-1):size-1;
  const headers=new Headers(response.headers);
  headers.delete('Content-Encoding');headers.set('Accept-Ranges','bytes');
  if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start>=size||end<start){
    headers.set('Content-Range','bytes */'+size);headers.set('Content-Length','0');
    return new Response(null,{status:416,headers});
  }
  headers.set('Content-Range',`bytes ${start}-${end}/${size}`);
  headers.set('Content-Length',String(end-start+1));
  return new Response(bytes.slice(start,end+1),{status:206,headers});
}
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET') return;
  const url=new URL(event.request.url);
  if(url.origin!==self.location.origin||!url.href.startsWith(self.registration.scope)) return;
  event.respondWith(caches.open(CACHE).then(cache=>cache.match(event.request,{ignoreSearch:true})).then(response=>response?cachedMediaRange(event.request,response):fetch(event.request)));
});
